language: java
dist: trusty

jdk:
  - oraclejdk8
  - openjdk14

addons:
  sonarcloud:
    organization: "ethauvin-github"

before_install:
  - chmod +x gradlew

after_success:
  - |
    if [ "${TRAVIS_TEST_RESULT}" == 0 ] && [ "$TRAVIS_JDK_VERSION" == "openjdk14" ]; then
      ./gradlew sonarqube
    fi
