image:
    - Visual Studio 2022

version: "{branch} {build}"
skip_tags: true

build:
  verbosity: detailed

download_script:
  - bld.bat download

test_script:
  - bld.bat compile test

branches:
  only:
    - master
    - 1.1.0-dev

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk17
  
matrix:
  fast_finish: true
