image:
    - Visual Studio 2019

version: "{branch} {build}"
skip_tags: true

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info --no-daemon

test_script:
  - gradlew.bat check --info --no-daemon

branches:
  only:
    - master
    - 1.0.6-dev

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk17
  - JAVA_HOME: C:\Program Files\Java\jdk11

matrix:
  fast_finish: true
