version: 2
defaults: &defaults
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb
    CI_NAME: "CircleCI"

defaults_gradle: &defaults_bld
  steps:
    - checkout
    - run:
        - name: Grant execute permission for bld
          command: chmod +x bld
    - run:
        - name: Download the dependencies
          command: ./bld download
    - run:
        - name: Run tests with bld
          command: ./bld c
jobs:
  bld_jdk17:
    <<: *defaults

    docker:
      - image: cimg/openjdk:17.0

    <<: *defaults_bld

  bld_jdk11:
    <<: *defaults

    docker:
      - image: cimg/openjdk:11.0

    <<: *defaults_bld

workflows:
  version: 2
  gradle:
    jobs:
      - bld_jdk11
      - bld_gradle_jdk17
