name: bld-ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build-bld-project:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17, 19, 20 ]

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}

      - name: Grant execute permission for bld
        run: chmod +x bld

      - name: Download the dependencies
        run: ./bld download

      - name: Run tests with bld
        run: ./bld compile jacoco

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        args: >
          -Dsonar.organization=ethauvin-github
          -Dsonar.projectKey=my-ethauvin_HttpStatus
          -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
          -Dsonar.jacoco.reportPath=build/jacoco/jacoco.exec
          -Dsonar.sources=src/main/java/
          -Dsonar.tests=src/test/java/
          -Dsonar.verbose=true

